### ISSUE TITLE
`download` command not working in Ruby 3.x.x

### ISSUE THREAD

**Issue by marcosdsanchez** [ankane/pghero_logs#1]
ruby version 3.0.3p157

```
/home/marcos/.local/share/gem/ruby/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `new'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/endpoints.rb:30:in `endpoints'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/endpoints.rb:22:in `hostname'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/configuration.rb:391:in `block in add_service'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/configuration.rb:344:in `block in add_option'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/configuration.rb:364:in `block (2 levels) in add_option_with_needs'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/configuration.rb:364:in `each'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/configuration.rb:364:in `inject'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/configuration.rb:364:in `block in add_option_with_needs'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/aws-sdk-v1-1.67.0/lib/aws/core/service_interface.rb:73:in `initialize'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/pghero_logs-0.1.0/lib/pghero_logs.rb:25:in `new'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/pghero_logs-0.1.0/lib/pghero_logs.rb:25:in `download'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/pghero_logs-0.1.0/lib/pghero_logs.rb:15:in `run'
	from /home/marcos/.local/share/gem/ruby/3.0.0/gems/pghero_logs-0.1.0/bin/pghero_logs:4:in `<top (required)>'
	from /home/marcos/.local/share/gem/ruby/3.0.0/bin/pghero_logs:25:in `load'
	from /home/marcos/.local/share/gem/ruby/3.0.0/bin/pghero_logs:25:in `<main>'
```

I think that the problem may be related to the following warning that appears when running the same command in versions  < 3

```
/home/marcos/.gem/ruby/3.0.0/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated 
```

**Comment by ankane** [comment]
Hey @marcosdsanchez, thanks for reporting! Fixed in the commit above, and will push a new release shortly.
